# Generated by Django 6.0.3 on 2026-04-24 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domaine',
            field=models.CharField(default='Informatique', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='statut_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé')], default='APPROUVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 'encadrant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
