# Generated by Django 6.0.3 on 2026-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_domaine_project_statut_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='statut_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
