# Generated by Django 5.2.12 on 2026-03-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_at',
        ),
    ]
