# Generated by Django 6.0.3 on 2026-04-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_assigned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.OneToOneField(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='final_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
