# Generated by Django 6.0.3 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_alter_wish_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='motivation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
