# Generated by Django 6.0.3 on 2026-05-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_wish_motivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='motivation',
        ),
    ]
